// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK2ZbfKdYk886t1XjpqMTDKZ_8gQvmUEg',
    appId: '1:381125793960:web:2ff588ddc9cecf8d058a9d',
    messagingSenderId: '381125793960',
    projectId: 'mingle-app-bc2c1',
    authDomain: 'mingle-app-bc2c1.firebaseapp.com',
    storageBucket: 'mingle-app-bc2c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqAq9YC9XuTgZ4kAclBy43xhVSJOP634',
    appId: '1:381125793960:android:606256024cc34b48058a9d',
    messagingSenderId: '381125793960',
    projectId: 'mingle-app-bc2c1',
    storageBucket: 'mingle-app-bc2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjntyskBp8Fey01fpFlt1PII6XnhwuELo',
    appId: '1:381125793960:ios:474908258d0faf9f058a9d',
    messagingSenderId: '381125793960',
    projectId: 'mingle-app-bc2c1',
    storageBucket: 'mingle-app-bc2c1.firebasestorage.app',
    iosBundleId: 'com.example.mingle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjntyskBp8Fey01fpFlt1PII6XnhwuELo',
    appId: '1:381125793960:ios:474908258d0faf9f058a9d',
    messagingSenderId: '381125793960',
    projectId: 'mingle-app-bc2c1',
    storageBucket: 'mingle-app-bc2c1.firebasestorage.app',
    iosBundleId: 'com.example.mingle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK2ZbfKdYk886t1XjpqMTDKZ_8gQvmUEg',
    appId: '1:381125793960:web:fce77f329580f935058a9d',
    messagingSenderId: '381125793960',
    projectId: 'mingle-app-bc2c1',
    authDomain: 'mingle-app-bc2c1.firebaseapp.com',
    storageBucket: 'mingle-app-bc2c1.firebasestorage.app',
  );
}
